### ISSUE TITLE
Can I teleport to outside of the country? 

### ISSUE THREAD

**Issue by POKEGO1234** [iam4x/pokemongo-webspoof#104]
I know teleporting too far would cause me to get soft-ban,
but is it possible to teleport outside of the country?

I can go anywhere inside my country, but when I try to get out of it, it gives me
"ZERO_RESULTS" error... :(

**Comment by giacomoalonzi** [comment]
ban risk?

**Comment by batteries** [comment]
I also have this problem. I am able to search for locations within my country (Taiwan), but since it is currently geo-blocked, I'd like to teleport to released countries. However, when I try to search for them in the search bar, I get a "Error with schedule trip, ZERO_RESULTS" error. How can I fix this?

**Comment by POKEGO1234** [comment]
Ok... so I guess I am not the only person who is having this trouble... I hope someone can answer this...

**Comment by Andr3sh** [comment]
I've played in NY a couple of times but with the new version (1.2) i can't teleport to any place in the US. If I try to search New York it gives me ZERO_RESULTS. But for example London and Paris work fine though...

**Comment by POKEGO1234** [comment]
For me, I tried everywhere in the world and it doesn't work but inside of my country....

**Comment by iam4x** [comment]
It's not working, it's a duplicated of #62 let's keep discussion centralised
