### ISSUE TITLE
Can't select Debug > Simulate Location >

### ISSUE THREAD

**Issue by hhuesca** [iam4x/pokemongo-webspoof#126]
Hi everyone;

I can't select any of the options on Simulate Location, i get this...

![captura de pantalla 2016-07-21 a las 10 06 32 a m](https://cloud.githubusercontent.com/assets/20577711/17027807/078df7f2-4f2b-11e6-963f-1702222c6e5a.png)

Your help is kindly appreciated. Thanks!

**Comment by AbelIngrand** [comment]
You must run the app on your iPhone before being able to select this option. Select your phone from the menu and click on the play button

**Comment by hhuesca** [comment]
Thank you very much! It's still not working but at least i can select location!

**Comment by zoofo** [comment]
I am having similar problems, however I can choose the different locations, but when I click pokemonLocation I get an error: "Location simulation cannot continue because the GPX file "pokemonLocation.gpx" is invalid". 

Also, I am not getting any map nor can't understand how I will move my character!

Thanks for the help!

**Comment by iam4x** [comment]
@zoofo Can you move once or map in that map, or teleport to somewhere to check if it happens on every location `pokemonLocation.gpx is invalid`

I'll close this since it's dup of #125
