### ISSUE TITLE
Memory issue:

### ISSUE THREAD

**Issue by jhoye88** [iam4x/pokemongo-webspoof#148]
Just noticed this, as I was running the app and then suddenly, i get ported back to my current physical location. I was doing walking speed, and was just about to engage a gym battle when I was teleported.

2016-07-22 00:02:55.189 pokemon-webspoof[40083:16152817] Received memory warning.
Message from debugger: Terminated due to memory issue

**Comment by evannudd** [comment]
This is due to how the app is running in the background. Over time when an app is in the background and hasn't specified that it's still in use the system will terminate it's memory. 
This issue has been fixed by a recent pull request but the download application hasn't been updated with the merge yet.

**Comment by jhoye88** [comment]
So there's no correlation between the app terminating and ingame actions? Because i find it very suspicious that each time it closes, it is because im either trying to catch a Pokemon or viewing a Gym.

**Comment by evannudd** [comment]
You just happen to be using more resources at the time, and using more resources may be affecting the application in other ways. But I am confident that the crash you're reporting is occurring due to the reason I previously mentioned. 
In the upcoming version the application is reconfigured to tell the system it's using audio in the background that way this error shouldn't occur anymore.

**Comment by jhoye88** [comment]
Ah excellent, i will be awaiting that release then in hope for it to be fixed! :)
