### ISSUE TITLE
Background audio not playing. 

### ISSUE THREAD

**Issue by evannudd** [iam4x/pokemongo-webspoof#155]
Put this line of code into xCode ViewController.m, line 33
    
    NSLog(@" %s", [backgroundAudioPlayer isPlaying] ? "true" : "false");

And when I run it I'm getting a false value. When ever play is called it's not actually running and it wasn't checked to make sure it's running.

**Comment by evannudd** [comment]
And I'm still getting the out of memory crash.

**Comment by h4v1nfun** [comment]
Just a thing checking if it's playing right next to the play call sometimes returns false because file hasn't start playing yet. 

Anyway i've made a pull request witch hopefully resolves the out of memory crash. With my code if you put that NSLog right before opening Pokemon GO it will return true.

**Comment by evannudd** [comment]
That's true, thank you.
