### ISSUE TITLE
Location simulation cannot continue because the GPX file "pokemonLocation.gpx" is invalid.

### ISSUE THREAD

**Issue by letungit90** [iam4x/pokemongo-webspoof#214]
Error message when run Debug->Simulate Location->pokemonLocation:
Location simulation cannot continue because the GPX file "pokemonLocation.gpx" is invalid.

**Comment by christianlepson** [comment]
Having the same issue

**Comment by lanabug** [comment]
Me too.

**Comment by Xjkstar** [comment]
me too

**Comment by khuangia** [comment]
I think just immediate close pokemon-go then restart webspoofapp, then everything goes well. I am wondering this issue is a normal case in QA testing.

**Comment by Mrpringles** [comment]
pokemonlocation.pgx  is blank :/

**Comment by Vanderebio** [comment]
Hi guys,
I had this problem before but I found out what I did wrong -- I tried to open the xcode project file directly instead of double clicking the .app file. 
If this is what you have done, try follow the instruction and open the app file, and you should see a desktop app open, showing a map and several buttons. 
If this is not your case, ignore me. 
Thanks to Max now I can stay at home and catch Pokemon everywhere. 
Cheers,
Yi

**Comment by Vanderebio** [comment]
Hi Nozk,
Instead of folk/download the project folder, download the zip file he gave in the description. The link is below the GIF:
"-> Download last release pokemongo-webspoof.app.tar.gz (v1.2.0)"
Yi

**Comment by iam4x** [comment]
This is only a warning, it will happen sometimes just ignore 👍

**Comment by johannesponader** [comment]
Issue could be raising here because http://www.cydiageeks.com/pokemon-go-mac-built-controller-webspoof.html is linking to https://github.com/iam4x/pokemongo-webspoof/archive/master.zip instead of pokemongo-webspoof.app.tar.gz
