### ISSUE TITLE
Error auto click Xcode

### ISSUE THREAD

**Issue by d3ath89** [iam4x/pokemongo-webspoof#271]
Hello all together

I install the new version of web spoof
but now i get the fooling Error Code in the LocationSpoof: -1719
The app didn't have the right authorization.

Could some one help me?
Thanks a lot!

**Comment by d3ath89** [comment]
i can update the location manually
but if i change the location in LocationSpoof the Xcode doesn't update the location in the app automatically

**Comment by uae980** [comment]
on your mac go to system preferences -----> security & privacy ----> tick next to pokemon webspoof

**Comment by g3crossfire** [comment]
@iam4x i found if you hit the "auto update xcode location" 10 times real quick and go to the xcode app it will have to load to catch up. once it stops loading you go back to the map app and all works no error.
its like you need to have xcode window up so that the process can start before it can work in the background...

**Comment by iam4x** [comment]
Hum that's weird behaviour @g3crossfire I can't reproduce :(
