### ISSUE TITLE
iPhone get very warm 

### ISSUE THREAD

**Issue by pcmore** [iam4x/pokemongo-webspoof#273]
Since the update my phone gets really warm after a few minutes playing pogo. Just seconds after closing it the phone cool down. What could it be? iOS 9.3.2

**Comment by FreshDonut** [comment]
Lower your brightness. Simply stated, the game is resource-intensive. Shouldn't do anything damaging to your phone even if you don't lower the brightness. Phones have an internal temperature sensor that automatically shuts the phone off if things get too hot. Haven't seen that happen since the time I left my phone in the sun while playing soccer.
