### ISSUE TITLE
Big problem

### ISSUE THREAD

**Issue by g3crossfire** [iam4x/pokemongo-webspoof#278]
Latest Pokemon go update can bypass this gps hack .
How to fix? Is there I wifi hack, modem hack?

**Comment by FreshDonut** [comment]
Give us more details. Was it working before? What iOS are you running? What have you tried? It's working just fine for me.

**Comment by alexpearce92** [comment]
Its not possible for Pokemon Go to "bypass the gps hack" since its your iPhone's GPS location that is being changed, not just the gps in PG. I would suggest playing around with webspoof and making sure your location is changing in Google Maps on your phone. Otherwise, we need more information about what you're experiencing to give you a tailored solution

**Comment by g3crossfire** [comment]
I have not had a problem with is glitching between my real location and the spoof one. Now it happens a lot. Not a bad now when I first posted this. Just got worried the first time it happen. 
Hope new update fixes so of the issues we all have.
