### ISSUE TITLE
teleporting

### ISSUE THREAD

**Issue by otyler46** [iam4x/pokemongo-webspoof#285]
I live in virginia and wanted to use pokemon go in new york. I got softbanned teleporting. Is there a technique that prevents or reduces the chance of a soft ban when teleporting?

**Comment by cronos45** [comment]
Teleport first then run xcode

**Comment by lukesnowden** [comment]
also note that any form of movement has to be viable via google maps api. i.e. UK residents cannot teleport to New York but they can to Paris.

**Comment by alexpearce92** [comment]
I found it useful to confirm my spoofed location by opening google maps on my phone before opening PG. I was able to play in Santa Monica Pier from Houston as a result without a soft ban

**Comment by Ladditron** [comment]
Alexpearce92 can you explain this a little more?

**Comment by alexpearce92** [comment]
The location spoofer here tricks the iPhone's GPS, not just Pokemon Go. So in order to make sure that the spoofing is working, I run everything from my computer and then check Google Maps on my phone to make sure that (1) I'm showing up in the location that the spoofer says I'm in, and (2) that when I move in the spoofer, I move in Google Maps. For me, this usually takes a few minutes of toggling on/off "Simulate Location: pokemon location" and "auto update xcode location" until its working. THEN I open pokemon go.
