### ISSUE TITLE
Failed to parse GPX file when clicking on Debug > Simulate location > pokemonLocation

### ISSUE THREAD

**Issue by mattdog0601** [iam4x/pokemongo-webspoof#324]
This error happens when I load the app and open the pokemonLocation gtx File.

**Comment by mattdog0601** [comment]
The full error is this: Location simulation cannot continue because the GPX file "pokemonLocation.gpx" is invalid.

**Comment by mattdog0601** [comment]
There is nothing written in the gtx file btw do I need to do that before I load the app??

**Comment by mattdog0601** [comment]
also there is no web spoof app. how do I open it. I clicked on the app.js in src and it opened an apple watch simulator with an error.

**Comment by krballard** [comment]
[https://github.com/iam4x/pokemongo-webspoof/releases/download/v1.2.0/pokemongo-webspoof-v120.app.tar.gz](https://github.com/iam4x/pokemongo-webspoof/releases/download/v1.2.0/pokemongo-webspoof-v120.app.tar.gz)

Did you download this?

**Comment by elvquant** [comment]
locking around my issue there is no menu entry "pokemonLocation" and I haven't found any "*.gpx" which are able to select in Xcode Debug menu ... I found: http://stackoverflow.com/questions/16780366/xcode-greys-out-gpx-files-in-filebox

May be the problem is for both issues (missing entry and unable to load gpx) are possible, that there is an misspelling contenttype-mapping on the system.

After installing a fresh minimal OS X 10.10 and Xcode 7.3.1 all works correctly!
The contenttype-mapping is now correct and the correct icon will shown.

Now I have to check, what I can do for my "regular" working system ...

**Comment by macdonjo** [comment]
Same issue here.

![image](https://cloud.githubusercontent.com/assets/2490900/17454487/ae18a0ea-5b65-11e6-9356-1a96aa2049ba.png)

**Comment by iam4x** [comment]
Should happen sometimes but it's non bloquant.
