### ISSUE TITLE
Can't interact with anything

### ISSUE THREAD

**Issue by schumannd** [iam4x/pokemongo-webspoof#33]
Hi,
I noticed the following problems when playing the game while spoofing your location:

- When trying to place a pokemon in a friendly gym, it closes with "Error" written in red.
- Pokemon always escape and run away instantly when caught
- Gym battles Are also not possible
- Spinning pokestops does not yield anything

**Comment by jessedobbelaere** [comment]
You have been soft-banned, which typically lasts between 15min and 2 hours. 
This is most likely because you "teleported" a lot of km's in a few seconds. Like if you jump between countries or go from San Francisco to New York. 

The solution is to make smaller jumps between locations, or which worked for me: close the Pokemon app for 15-30minutes (traveltime), then adjust your location to a different country and open it again. Just don't jump to locations in a timeframe the fastest plane would not be able to take you. 

Anyway wait a bit and restart the app and you should have a working game again. Hopefully they will never cancel accounts after X softbans.

**Comment by schumannd** [comment]
Ok, thanks. I jsut read about this. Maybe it should be mentioned in the readme
