### ISSUE TITLE
Development mode 

### ISSUE THREAD

**Issue by ngoclt** [iam4x/pokemongo-webspoof#364]
Firstly, I would like to thank you for your work on this tool. Have to say that this a really great idea. 

I am also a developer, my experience is about mobile app development however I have some JS / React skill. So I would like to participate to develop this tool. However, I'm facing with a installing problem, below is the error log when I tried to run **npm run build**

`Downloading electron-v0.4.1-darwin-x64.zip
Error: GET https://github.com/electron/electron/releases/download/v0.4.1/electron-v0.4.1-darwin-x64.zip returned 404
Failed to find Electron v0.4.1 for darwin-x64 at https://github.com/electron/electron/releases/download/v0.4.1/electron-v0.4.1-darwin-x64.zip`

I'm using MAC OS El Capitan (10.11.5)

Thanks in advance,

**Comment by b-admike** [comment]
@ngoclt I was also facing that issue, and I think that electron version is outdated (and I couldn't find the link), so what I did was I looked that the project has a dep on `electron-prebuilt` versions `^1.2.7` https://github.com/iam4x/pokemongo-webspoof/blob/master/package.json#L39, so I changed the electron dep version to the same i.e. changed https://github.com/iam4x/pokemongo-webspoof/blob/master/package.json#L37 to `^1.2.7`. This, of course, is bad, since we don't know if versions `1.2.7` and above of `electron` are compatible with the project. But, once I did that and removed `node_modules` and ran `npm i` again, `npm run build` succeeded for me.
```
| => npm run build

> pokemongo-webspoof@1.2.0 build /Users/badmike/pokemongo-webspoof
> npm run clean && npm run build:code && npm run build:electron && npm run archive:app


> pokemongo-webspoof@1.2.0 clean /Users/badmike/pokemongo-webspoof
> rm -rf ./dist/* ./pokemongo-webspoof-darwin-x64 ./pokemongo-webspoof.zip


> pokemongo-webspoof@1.2.0 build:code /Users/badmike/pokemongo-webspoof
> NODE_ENV=production webpack --config webpack.config.babel.js

Hash: f54e68b024e98ce57645
Version: webpack 2.1.0-beta.20
Time: 15300ms
   Asset    Size  Chunks             Chunk Names
index.js  655 kB       0  [emitted]  main
 [615] multi main 40 bytes {0} [built]
    + 615 hidden modules

> pokemongo-webspoof@1.2.0 build:electron /Users/badmike/pokemongo-webspoof
> electron-packager . pokemongo-webspoof --platform=darwin --arch=x64

Packaging app for platform darwin x64 using electron v1.3.2
Wrote new app to /Users/badmike/pokemongo-webspoof/pokemongo-webspoof-darwin-x64

> pokemongo-webspoof@1.2.0 archive:app /Users/badmike/pokemongo-webspoof
> tar czf pokemongo-webspoof.app.tar.gz ./pokemongo-webspoof-darwin-x64/pokemongo-webspoof.app
```

**Comment by ngoclt** [comment]
@b-admike : Thank you very much for your reply. 
I can build the app successfully now. 

PS: I believe you mean line 36 in the package.json file :)
https://github.com/iam4x/pokemongo-webspoof/blob/master/package.json#L37
