### ISSUE TITLE
Pokestops, gyms don't work and pokemons run after first ball

### ISSUE THREAD

**Issue by Pokegopla** [iam4x/pokemongo-webspoof#58]
Does anyone else have this problem? 

Or is there a solution?

**Comment by aekanman** [comment]
This happens when you change your location too often and/or to a place that is really far, or in other words unrealistically. As a result, you get a soft ban that doesn't let you catch any pokemon or farm any pokestops. Wait for a while, it'll start working and then make more realistic location changes.

**Comment by Pokegopla** [comment]
O oke thanks.

**Comment by aekanman** [comment]
#closed
